#!/bin/bash

usage()
{
  echo ""
  echo "Need to specify version. E.g: 'abqtest 17' to run tests with Abaqus 2017 "
}

if [ "$1" == "" ]; then
    usage
    exit 1
fi

CMD="bin/startest -a abaqus -ne -jvmargs -DmanifestFile=/u/cd8rit/database/abq$1.json -jvmargs -Dabaqus=20$1 -deleteOnExit"
echo "Running command:"
echo $CMD

eval $CMD
