#!/bin/sh

if [ "$1" ]; then
  EXTRA="$1-"
else
  EXTRA=
fi
BACKUPDIR="$HOME/backup/tmp"
TARDIR="$HOME/backup"
DATESTAMP=`date +%Y-%m-%d-%H-%M`
CURRDIR=`pwd`
TOPDIR=`basename $CURRDIR`
TARFILE="$TARDIR/$TOPDIR-$EXTRA$DATESTAMP.tar.bz2"

if [ -d "$BACKUPDIR" ] ; then
  echo "rm -rf $BACKUPDIR"
  rm -rf $BACKUPDIR
  echo
fi

FILES=`ls -1 | grep -v 'lib$' | xargs echo`

for f in $FILES
do
  FILENAME=`basename $f`
  DIR=`dirname $f`
  echo "$FILENAME:"
  if [ ! -d $BACKUPDIR/$DIR ] ; then
    echo "mkdir -vp $BACKUPDIR/$DIR"
    mkdir -vp $BACKUPDIR/$DIR
  fi
  if [ -f "$f" ] ; then
    echo "cp -v $f $BACKUPDIR/$DIR"
    cp -v $f $BACKUPDIR/$DIR
    echo
  elif [ -d "$f" ] ; then
    echo "cp -rv $f $BACKUPDIR/$DIR"
    cp -rv $f $BACKUPDIR/$DIR
    echo
  else
    echo "WARNING: Missing file: $f"
  fi
done

if [ -f "$TARFILE" ] ; then 
  echo rm -vf $TARFILE
  rm -vf $TARFILE
  echo
fi

( cd $BACKUPDIR ; tar cvjf $TARFILE * )

ls -l $TARFILE

