#!/bin/sh

CFGFILE="getSource.cfg"
CVSROOT=194.193.148.45:/cvs3/src ; export CVSROOT
CVSNAME=
NAME=
BASELINE=
if [ -f "${CFGFILE}" ] ; then
  echo "Found configurarion file:" 
  ls -l ${CFGFILE}
  . getSource.cfg
  BASELINE=$1
else
  CVSNAME=$1
  BASELINE=$2
fi

if [ "${CVSNAME}" ] ; then
  echo "CVSNAME=${CVSNAME}"
else
  echo "ERROR: Can not find cvs name"
  exit 4
fi

if [ "${NAME}" ] ; then
  OUTDIR="-d `basename ${CVSNAME}`"
  TOPDIRNAME=${NAME}
else
  OUTDIR=""
  TOPDIRNAME=${CVSNAME}
fi

if [ "${BASELINE}" ] ; then
  echo "Preparing baseline $BASELINE"
  BRANCH="-r $BASELINE"
  TOPDIR=$BASELINE
  TARBALL=${BASELINE}.tar.bz2
else
  DATE=`date +%Y-%m-%d`
  if [ "${BRANCHNAME}" ] ; then
    echo "Using current version source from ${BRANCHNAME}" 
    TOPDIR=${TOPDIRNAME}-${BRANCHNAME}_${DATE}
    BRANCH="-r ${BRANCHNAME}"
  else
    echo "Using current version source from trunk" 
    TOPDIR=${TOPDIRNAME}-trunk_${DATE}
    BRANCH=
  fi
  TARBALL=${TOPDIR}.tar.bz2
fi
echo "Using ${TOPDIR} as code name"

if [ -d "${TOPDIR}" ] ; then
  echo "Removing previous version in directory ${TOPDIR}"
  rm -rf ${TOPDIR}
fi
if [ -f "${TARBALL}" ] ; then
  echo "Removing previous tarball ${TARBALL}"
  rm -f ${TARBALL}
fi

echo
mkdir ${TOPDIR}

echo
cd ${TOPDIR}

echo


echo "cvs co -P ${OUTDIR} ${BRANCH} ${CVSNAME}"
cvs co -P ${OUTDIR} ${BRANCH} ${CVSNAME}

if [ -f "$TOPDIRNAME/Makefile" ] ; then
  HAS_SOURCE_RULE=`grep '^source:' $TOPDIRNAME/Makefile` 
  if [ "$HAS_SOURCE_RULE" ] ; then
    echo
    cd ${TOPDIRNAME}

    echo
    echo "make source"
    make source

    echo
    cd ..
  fi
elif [ -f "$TOPDIRNAME/tools/autobuild" ] ; then
  echo
  echo "$TOPDIRNAME/tools/autobuild -mktools"
  $TOPDIRNAME/tools/autobuild -mktools
fi

echo
cd ..

echo
echo "tar cjf ${TARBALL} ${TOPDIR}"
tar cjf ${TARBALL} ${TOPDIR}

