#!/bin/bash

if [ -z "$DEV_HOME" ] ; then
  . ~/bin/setrel
  make clean
  make MODULES=coSimulationAbaqus
fi

NP="-np 4"
SUFFIX="-configure"

run_abaqus()
{
  ##echo bin/startest $NP -ma $1 -g licensed3rdparty $SUFFIX
  ##bin/startest $NP -ma $1 -g licensed3rdparty $SUFFIX
  ##SUFFIX="-append"
  echo bin/startest -ma $1 -g licensed3rdparty $NP -timestamp abaqus -baselineshome $DEV_HOME/baselines-rel/10.04 -datahome $DEV_HOME/startestdata-rel/10.04
  bin/startest -ma $1 -g licensed3rdparty $NP -timestamp abaqus -baselineshome $DEV_HOME/baselines-rel/10.04 -datahome $DEV_HOME/startestdata-rel/10.04
}


# 9.65s
#run_abaqus coSimulationAbaqus.BaffleTest
# 8.70s
#run_abaqus coSimulationAbaqus.Baffle2Test
# 12.41s
#run_abaqus coSimulationAbaqus.BaffleRemesh2Test
# i7.60s
#run_abaqus coSimulationAbaqus.BaffleRestart2Test

# 1.25s
#run_abaqus coSimulationAbaqus.BlockAbqExpTest
# 0.90s
#run_abaqus coSimulationAbaqus.BlockAbqExp2Test
# 0.67s
#run_abaqus coSimulationAbaqus.BlockMapConfigTest
# 0.66s
#run_abaqus coSimulationAbaqus.BlockMapConfig2Test
# 0.73s
#run_abaqus coSimulationAbaqus.BlockPreLoadTest
# 0.69s
run_abaqus coSimulationAbaqus.BlockUnits2_inTest
# 0.70s
run_abaqus coSimulationAbaqus.BlockUnits2_mmTest
# 0.69s
run_abaqus coSimulationAbaqus.BlockUnits_inTest
# 0.72s
run_abaqus coSimulationAbaqus.BlockUnits_mmTest

# 6.76s
#run_abaqus coSimulationAbaqus.BoxDrop2Test
# 23 min
#run_abaqus coSimulationAbaqus.BrakeValveElbowOversetTest
# 2.84s
#run_abaqus coSimulationAbaqus.BrakeValveWedgeTest
# 2.78s
#run_abaqus coSimulationAbaqus.BrakeValveWedge2Test
# 2.34s
run_abaqus coSimulationAbaqus.CavityBlockTest
# 0.80s
run_abaqus coSimulationAbaqus.CosimMapError2Test
# s
#run_abaqus coSimulationAbaqus.DoublePlateViVZones2Test
# s
#run_abaqus coSimulationAbaqus.ManifoldFILMTest
# s
#run_abaqus coSimulationAbaqus.ManifoldFILM2Test
# 3.10s
run_abaqus coSimulationAbaqus.MultiRegionDSTest
# 3.02s
run_abaqus coSimulationAbaqus.MultiRegionDS2Test
# 3.74s
run_abaqus coSimulationAbaqus.RotateSphere2Test
# 7.13s
#run_abaqus coSimulationAbaqus.PlateRemesh2Test
# s
#run_abaqus coSimulationAbaqus.PorousBaffleTest

## 32.73s
#run_abaqus coSimulationAbaqus.PipeVibrateExplTest
## 26.72s
#run_abaqus coSimulationAbaqus.PipeVibrateImplTest
## 22.94s
#run_abaqus coSimulationAbaqus.PipeVibrateImpl2Test
## 22.33s
#run_abaqus coSimulationAbaqus.PlateViVDSZones2Test
## 156.04s
#run_abaqus coSimulationAbaqus.TurekHronFSI3Test


#bin/startest -runtests
