#!/bin/bash

TYPES="fix feat build chore ci docs test perf refactor style"
TYPES_HELP=`echo $TYPES | sed 's/ /|/g'`


if [ $# -lt 4 ] ; then
  echo "Usage: $0 <${TYPES_HELP}> <JIRA> <Scope> <Message> [Yes]" 	 
  exit 1 
fi

TYPE=$1
shift
JIRA=$1
shift
SCOPE=$1
shift
MSG=$1
shift

EXEC=No
if [ $# -gt 0 ] ; then
  EXEC=$1
  shift
fi

VALID_TYPE=`echo $TYPES | grep -w $TYPE`
if [ -z "${VALID_TYPE}" ]; then
    echo "Wrong type $TYPE. Must be one of: ${TYPES}"
    exit
fi

BNAME="$TYPE/$JIRA-$SCOPE"

if [ "$EXEC" != "Yes" ] ; then
  git remote -v
  echo
fi

echo git checkout -b $BNAME
if [ "$EXEC" == "Yes" ] ; then
  git checkout -b $BNAME
  sleep 2
fi

echo git add .
if [ "$EXEC" == "Yes" ] ; then
    git add .
  sleep 2
fi

FULL_MSG="$TYPE($SCOPE): $JIRA - $MSG"
echo git commit -m \""$FULL_MSG"\"
if [ "$EXEC" == "Yes" ] ; then
    git commit -am "$TYPE($SCOPE): $JIRA - $MSG"
  sleep 2
fi

# Create branch on remote and set your local up to track it
echo git push -u origin $BNAME
if [ "$EXEC" == "Yes" ] ; then
  git push -u origin $BNAME
fi

MASTER=`git remote show origin | grep 'HEAD branch:' | cut -d' ' -f5`
GITUSER=`git config user.email | cut -d@ -f1`

echo glab mr create --target-branch $MASTER --description "\"${FULL_MSG}\"" --title "\"$MSG\"" --draft --remove-source-branch -a "\"$GITUSER\""
if [ "$EXEC" == "Yes" ] ; then
  glab mr create --target-branch $MASTER --description "${FULL_MSG}" --title "$MSG" --draft --remove-source-branch -a "$GITUSER"
fi
