#!/bin/bash

if [ $# -lt 3 ] ; then
  echo "Usage: $0 <JIRA> <Branch Name> <Message> [Yes]" 	 
  exit 1 
fi

JIRA=$1
shift
NAME=$1
shift
MSG=$1
shift

EXEC=No
if [ $# -gt 0 ] ; then
  EXEC=$1
  shift
fi
#UNAME=`whoami`
# echo "MSG=$MSG"
# echo "Num arg: $#" 

BNAME="fix/$NAME"

if [ "$EXEC" != "Yes" ] ; then
  git remote -v
  echo
fi

echo git checkout -b $BNAME
if [ "$EXEC" == "Yes" ] ; then
  git checkout -b $BNAME
  sleep 2
fi

echo git add .
if [ "$EXEC" == "Yes" ] ; then
    git add .
  sleep 2
fi

FULL_MSG="fix($NAME): $JIRA - $MSG"
echo git commit -m \""$FULL_MSG"\"
if [ "$EXEC" == "Yes" ] ; then
    git commit -am "fix($NAME): $JIRA - $MSG"
  sleep 2
fi

# Create branch on remote and set your local up to track it
echo git push -u origin $BNAME
if [ "$EXEC" == "Yes" ] ; then
  git push -u origin $BNAME
fi

MASTER=`git remote show origin | grep 'HEAD branch:' | cut -d' ' -f5`
echo "MASTER=$MASTER"


echo glab mr create --target-branch $MASTER --description "\"${FULL_MSG}\"" --title "\"$MSG\"" --squash-before-merge --remove-source-branch -a "\"$GITUSER\""
if [ "$EXEC" == "Yes" ] ; then
  glab mr create --target-branch $MASTER --description "${FULL_MSG}" --title "$MSG" --squash-before-merge --remove-source-branch -a "$GITUSER"
fi
