#!/bin/sh

/usr/bin/vncserver -kill :1
#/usr/bin/vncserver -geometry 1400x1000 :1
#/usr/bin/vncserver -alwaysshared -geometry 1600x1100
/usr/bin/vncserver -alwaysshared -geometry 1900x1140
/usr/bin/vncviewer -shared zagor:1
