#!/bin/sh

DIR=$1
RATE=$2
PNG=`ls -1 $DIR/*.png | head -1`
PNG=`echo $PNG | sed -e 's/[.]png$//' | sed -e 's/[0-9]*$//'`
PNG="$PNG%5d.png"
MP4BASE=$DIR
echo "PNG=$PNG"
echo "MP4BASE=$MP4BASE"

rm -f $MP4BASE.mp4

cmd="ffmpeg -r $RATE -i $PNG -an -r $RATE -q:v 5 -profile:v high -c:v libx264 -pix_fmt yuv420p $MP4BASE.mp4"
#cmd="ffmpeg -r 1 -pattern_type glob -i '*.png' -q:v 5 -profile:v high -c:v libx264 -crf 10 -pix_fmt yuv420p $MP4BASE.mp4"
echo $cmd
exec $cmd
