#!/bin/sh

# print and then execute a command
echo_command() {
  [ $verbose ] && echo "$@"
  "$@"
  if [ $? -ne 0 ] ; then
    echo "ERROR: $@ failed!!!"  
    exit 4
  else
    echo
  fi
}

TESTLOOP=$1
NAME=`echo $TESTLOOP | cut -d. -f1`
echo "Setting up $NAME"
TLDIST=/users/cvs2/build/test/2009
TESTALL=testall
TESTTUT=testtut
verbose=yes

cd `dirname $0`
CWD=`pwd`


if [ ! -f "$TLDIST/$TESTLOOP" ] ; then
  echo "Can not find $TLDIST/$TESTLOOP"
  exit 4
fi

if [ -d "$NAME" ] ; then
  echo_command rm -rf $NAME
fi

echo_command mkdir $NAME

echo_command cp $TLDIST/$TESTLOOP . 

echo_command cd $NAME

echo_command tar xzvf ../$TESTLOOP

echo_command mv test $TESTALL

echo "Cleaning 404 stuff"
echo_command rm -rf $TESTALL/*404
echo_command rm -rf $TESTALL/*/*404
echo_command rm -rf $TESTALL/*/*/*404

echo_command cp $CWD/TestLoopComPNP $TESTALL/AATestLoop/TestLoopComPNP 
echo_command cp $CWD/TestLoop $TESTALL/AATestLoop/TestLoop 
echo_command cp $CWD/go $TESTALL/AATestLoop/go 

echo_command mkdir $TESTTUT
echo_command mkdir $TESTTUT/AATestLoop
echo_command cp -r $TESTALL/AATestLoop/Cases* $TESTTUT/AATestLoop
echo_command cp -r $TESTALL/AATestLoop/Reports $TESTTUT/AATestLoop
echo_command cp -r $TESTALL/AATestLoop/DEBUG $TESTTUT/AATestLoop
LINKS="RunAll4 TestLoopComSTAT.org TestLoopComSTAT TestLoopComPNP.org TestLoopComPNP.new TestLoop TestLoopComPNP go"
echo_command cd $TESTTUT/AATestLoop
for LINK in $LINKS
do
  echo_command ln -s ../../$TESTALL/AATestLoop/$LINK
done
echo_command cd ../../
echo_command mv $TESTALL/Tuts405 $TESTTUT 








