#!/bin/bash

#TEST=coSimulationStarBasicOperations
#TIMESTAMP="-timestamp basic"

#TEST=coSimulationStarccm

TEST=coSimulationStarccm,coSimulationStarccm2,coSimulationStarBasicOperations,coSimulationAPI,coSimulationRestart,coSimulationStarPhysics,coSimulationVibratingPipe
TIMESTAMP="-timestamp all"

make MODULES="coSimulationStarccm coSimulationStarccm2 coSimulationStarBasicOperations coSimulationAPI coSimulationRestart coSimulationStarPhysics coSimulationVibratingPipe"

bin/startest $TIMESTAMP -m $TEST
bin/startest $TIMESTAMP -m $TEST
bin/startest $TIMESTAMP -m $TEST
bin/startest $TIMESTAMP -m $TEST
bin/startest $TIMESTAMP -m $TEST -np 2
bin/startest $TIMESTAMP -m $TEST -np 2
bin/startest $TIMESTAMP -m $TEST -np 3
bin/startest $TIMESTAMP -m $TEST -np 3
bin/startest $TIMESTAMP -m $TEST -np 4
bin/startest $TIMESTAMP -m $TEST -np 4
bin/startest $TIMESTAMP -m $TEST -np 5
bin/startest $TIMESTAMP -m $TEST -np 5
bin/startest $TIMESTAMP -m $TEST
