#!/bin/sh

HOST=`basename $0`

if [ "$HOST" = "sw2b" ] ; then
  if [ "$1" ] ; then
    AT_IN_ARG1=`echo $1 | grep '@'`  
    if [ "$AT_IN_ARG1" ] ; then
      NEWUSER=`echo $1 | cut -d'@' -f1`
      HOST=`echo $1 | cut -d'@' -f2`
    else
      NEWUSER=builder
      HOST=$1
    fi
    shift
  else
    echo "sw2b (user@host | host)"
    echo "   sw2b sava@titanic"
    exit 4
  fi
else
  NEWUSER=builder
fi

echo ssh -X -l $NEWUSER $HOST "$*"
ssh -X -l $NEWUSER $HOST "$*"

